### ISSUE TITLE
Tags aren't always closing

### ISSUE THREAD

**Issue by PedroC88** [frandi/TidyHtml5Managed#1]
The result I get from running your example is not perfect xml, I can't load result into an `XmlDocument` after running:

```
document.OutputBodyOnly = AutoBool.Yes;
document.Quiet = true;
document.CleanAndRepair();
string result = document.Save();
```

Note that I was using an older version of Tidy `HTML Tidy for Windows released on 25 March 2009` (but I was having issues with the limitations of a console application) and it worked without any parameters.

**Comment by frandi** [comment]
@PedroC88 can you share the input xml?

**Comment by PedroC88** [comment]
Hey Guys, sorry for the little information, I was in a bit of a rush at the time and couldn't stop to post more detail, digressing.

If you run the example code against the example input text `<p>Test` it works good, the problem is when there are open self-closing tags such as `link` or `img`, feeding the following html into the library

```
<html>
    <head></head>
    <body>
        <link href="#" rel="#">
        <img src="#">
        <hr>
    </body>
</html>
```

results in the following:

```
<!DOCTYPE html>
<html>
    <head>
        <meta name="generator" content="HTML Tidy for HTML5 for Windows version 5.1.25">
        <title></title>
    </head>
    <body>
        <link href="#" rel="#"><img src="#">
        <hr>
    </body>
</html>
```

where `link`, `img` and `hr` should be self-closed.

P.D. That isn't my real input, but the actual input is quite large so this is much easier to work with.

**Comment by PedroC88** [comment]
Correction, I was running the console tidy with 1 parameter `--output-xml yes` which was self-closing those tags as XML doesn't allow open tags as HTML does, simply changing my code to:

```
document.OutputBodyOnly = AutoBool.Yes;
document.Quiet = true;
document.OutputXml = true;
document.CleanAndRepair();
string result = document.Save();
```

(adding the call to `OutputXml`) fixed my issue.

Sorry for this guys.

**Comment by frandi** [comment]
@PedroC88 glad you finally solved the issue. We'll see if more complete documentation can be provided to avoid confusion in the future.
