### ISSUE TITLE
Building with higher level of compatability than required

### ISSUE THREAD

**Issue by grexican** [frandi/TidyHtml5Managed#2]
I'm using your nuget package. It is targetted at .NET v4.6, which is a pretty high version requirement. Can you try changing your version (as low as possible, for highest compatability) and re-releasing the package?

For now I'll build myself and use an external lib reference. But I'd prefer to do it cleanly with nuget. Thanks!

**Comment by frandi** [comment]
Hey man, thanks for the input. As Microsoft is dropping support for .Net 4, 4.5, and 4.5.1 (https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/), do you think re-targeting to .Net 4.5.2 make sense?

**Comment by grexican** [comment]
Sorry I didn't get an email notification saying you responded. I was just coming back to check up on this!

While I know they're dropping support for it, I think it makes sense to target for the the lowest possible version still, because developers still have those target profiles. I also don't think it hurts you in any way to target for a lower version, do you? It should just mean a higher level of compatibility and more potential users being able to use your library, no?

**Comment by frandi** [comment]
Sure, I'm finding a time to do it. Thanks.

**Comment by frandi** [comment]
TidyHtml5Managed v1.1.0 has been released to support multiple .Net versions targeting.
